services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smf
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ui:
    image: registry.home:80/smf-ui:latest
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000/api"

  api:
    image: registry.home:80/smf-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/smf"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
